// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoUnKYiDkzLLYWiE7c2x3cfnHVXAmN51o',
    appId: '1:458199360782:web:cdaf5f62a18d37f9f7235f',
    messagingSenderId: '458199360782',
    projectId: 'abcd-d6e60',
    authDomain: 'abcd-d6e60.firebaseapp.com',
    databaseURL: 'https://abcd-d6e60-default-rtdb.firebaseio.com',
    storageBucket: 'abcd-d6e60.appspot.com',
    measurementId: 'G-FMZJ0XRHQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAMX_6XWJFwouwijKlMMrfLjAZf3p2kQo',
    appId: '1:458199360782:android:168355be6aabc657f7235f',
    messagingSenderId: '458199360782',
    projectId: 'abcd-d6e60',
    databaseURL: 'https://abcd-d6e60-default-rtdb.firebaseio.com',
    storageBucket: 'abcd-d6e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt1WfeOPXTS2e6B9ueszzOXA3Pvhr-heE',
    appId: '1:458199360782:ios:a6c2ad50c204cfb9f7235f',
    messagingSenderId: '458199360782',
    projectId: 'abcd-d6e60',
    databaseURL: 'https://abcd-d6e60-default-rtdb.firebaseio.com',
    storageBucket: 'abcd-d6e60.appspot.com',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt1WfeOPXTS2e6B9ueszzOXA3Pvhr-heE',
    appId: '1:458199360782:ios:a6c2ad50c204cfb9f7235f',
    messagingSenderId: '458199360782',
    projectId: 'abcd-d6e60',
    databaseURL: 'https://abcd-d6e60-default-rtdb.firebaseio.com',
    storageBucket: 'abcd-d6e60.appspot.com',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoUnKYiDkzLLYWiE7c2x3cfnHVXAmN51o',
    appId: '1:458199360782:web:c0602fda788eabe3f7235f',
    messagingSenderId: '458199360782',
    projectId: 'abcd-d6e60',
    authDomain: 'abcd-d6e60.firebaseapp.com',
    databaseURL: 'https://abcd-d6e60-default-rtdb.firebaseio.com',
    storageBucket: 'abcd-d6e60.appspot.com',
    measurementId: 'G-LE0BZSN1TJ',
  );
}
